"""Constants for model-selection service orchestration."""

MODERN_LABELS_BENCHMARK_PRESET = "modern_labels_benchmark_v1"
MODEL_MODERN_LABELS_BENCHMARK_ALERT_EVENT_TYPE = (
    "model_modern_labels_benchmark_alert"
)
MODERN_LABELS_BENCHMARK_MODEL_FAMILIES = [
    "linear_ridge",
    "beta_regression",
    "additive_spline",
    "xgboost",
]
MODERN_LABELS_BENCHMARK_ALPHAS = [0.35, 0.75, 1.5]
MODERN_LABELS_BENCHMARK_KNOT_COUNTS = [2, 4]
MODERN_LABELS_BENCHMARK_LEARNING_RATES = [0.05, 0.1]
MODERN_LABELS_BENCHMARK_ESTIMATOR_COUNTS = [24]
MODERN_LABELS_BENCHMARK_MAX_DEPTHS = [2, 3]
MODERN_LABELS_BENCHMARK_MIN_LEAF_SIZES = [1]
MODERN_LABELS_BENCHMARK_MIN_SPLIT_GAINS = [0.0]
MODERN_LABELS_BENCHMARK_EARLY_STOPPING_ROUNDS = 4
